services: 
  relayer:
    image: us-central1-docker.pkg.dev/oxbow-406621/privacy-pools-core/staging/relayer
    serviceAccount: relayer-staging
    command: node
    args: ["dist/index.js"]
    environment:
      - name: CONFIG_PATH
        value: /etc/secrets/config.json
      - name: CHAIN_11155111_RPC_URL
        valueFrom:
          secretKeyRef:
            name: relayer-config-staging
            key: CHAIN_11155111_RPC_URL
      - name: DESTINATION_OP_RPC_URL
        valueFrom:
          secretKeyRef:
            name: relayer-config-staging
            key: DESTINATION_OP_RPC_URL
      - name: DESTINATION_BASE_RPC_URL
        valueFrom:
          secretKeyRef:
            name: relayer-config-staging
            key: DESTINATION_BASE_RPC_URL
      - name: DESTINATION_ARB_RPC_URL
        valueFrom:
          secretKeyRef:
            name: relayer-config-staging
            key: DESTINATION_ARB_RPC_URL
      - name: DESTINATION_STARKNET_RPC_URL
        valueFrom:
          secretKeyRef:
            name: relayer-config-staging
            key: DESTINATION_STARKNET_RPC_URL
      - name: RELAYER_PRIVATE_KEY
        valueFrom:
          secretKeyRef:
            name: relayer-config-staging
            key: RELAYER_PRIVATE_KEY
      - name: DESTINATION_OP_PRIVATE_KEY
        valueFrom:
          secretKeyRef:
            name: relayer-config-staging
            key: DESTINATION_OP_PRIVATE_KEY
      - name: DESTINATION_BASE_PRIVATE_KEY
        valueFrom:
          secretKeyRef:
            name: relayer-config-staging
            key: DESTINATION_BASE_PRIVATE_KEY
      - name: DESTINATION_ARB_PRIVATE_KEY
        valueFrom:
          secretKeyRef:
            name: relayer-config-staging
            key: DESTINATION_ARB_PRIVATE_KEY
      - name: DESTINATION_STARKNET_PRIVATE_KEY
        valueFrom:
          secretKeyRef:
            name: relayer-config-staging
            key: DESTINATION_STARKNET_PRIVATE_KEY
    resources:
      cpu: 100m
      memory: 2Gi

    service:
      type: ClusterIP
      port: 80
      protocol: TCP
      targetPort: 3000

    secretMounts:
    - name: relayer-config-staging
      mount: /etc/secrets/

    ingress:
      host: testnet-relayer.privacypools.com
      paths:
      - /
      tls:
        - secretName: privacypools-tls
          hosts:
            - testnet-relayer.privacypools.com
